"""Tests for the AIProviderKey ORM model — insert, uniqueness, masking, encryption."""

import pytest
from sqlalchemy.exc import IntegrityError

from agentic_project_service.db import db
from agentic_project_service.models.tenant import AIProviderKey
from agentic_project_service.services.encryption import (
    decrypt_api_key,
    encrypt_api_key,
    mask_api_key,
)


class TestAIProviderKeyInsertAndRead:
    def test_insert_and_to_dict(self, app):
        """Insert a row and verify to_dict() returns masked key."""
        plaintext = "sk-test-1234567890abcdef"
        encrypted = encrypt_api_key(plaintext)

        with app.app_context():
            row = AIProviderKey(provider="openai", api_key_encrypted=encrypted)
            db.session.add(row)
            db.session.commit()

            fetched = db.session.get(AIProviderKey, row.id)
            result = fetched.to_dict()

        assert result["provider"] == "openai"
        assert result["is_valid"] is True
        # Masked key starts with first 3 chars of plaintext and uses "..." separator
        # (mask_api_key returns f"{key[:3]}...{key[-4:]}").
        assert result["masked_key"].startswith("sk-")
        assert "..." in result["masked_key"]
        # Full plaintext must NOT appear in the masked form
        assert plaintext not in result["masked_key"]

    def test_id_is_auto_generated(self, app):
        """UUID primary key is generated by the server."""
        encrypted = encrypt_api_key("sk-auto-uuid-test")
        with app.app_context():
            row = AIProviderKey(provider="anthropic", api_key_encrypted=encrypted)
            db.session.add(row)
            db.session.commit()
            assert row.id is not None

    def test_is_valid_defaults_to_true(self, app):
        """is_valid defaults to True on insert."""
        encrypted = encrypt_api_key("sk-valid-default")
        with app.app_context():
            row = AIProviderKey(provider="google", api_key_encrypted=encrypted)
            db.session.add(row)
            db.session.commit()
            fetched = db.session.get(AIProviderKey, row.id)
            assert fetched.is_valid is True

    def test_last_validated_at_is_null_by_default(self, app):
        """last_validated_at is NULL on insert."""
        encrypted = encrypt_api_key("sk-null-validated")
        with app.app_context():
            row = AIProviderKey(provider="openrouter", api_key_encrypted=encrypted)
            db.session.add(row)
            db.session.commit()
            fetched = db.session.get(AIProviderKey, row.id)
            assert fetched.last_validated_at is None


class TestAIProviderKeyUniqueness:
    def test_duplicate_provider_raises_integrity_error(self, app):
        """Two rows with the same provider must raise IntegrityError."""
        encrypted = encrypt_api_key("sk-dupe-test")
        with app.app_context():
            row1 = AIProviderKey(provider="openai", api_key_encrypted=encrypted)
            db.session.add(row1)
            db.session.commit()

            row2 = AIProviderKey(provider="openai", api_key_encrypted=encrypt_api_key("sk-other"))
            db.session.add(row2)
            with pytest.raises(IntegrityError):
                db.session.commit()
            db.session.rollback()

    def test_different_providers_allowed(self, app):
        """Two rows with different providers are both accepted."""
        with app.app_context():
            db.session.add(
                AIProviderKey(provider="openai", api_key_encrypted=encrypt_api_key("k1"))
            )
            db.session.add(
                AIProviderKey(provider="anthropic", api_key_encrypted=encrypt_api_key("k2"))
            )
            db.session.commit()

            count = db.session.query(AIProviderKey).count()
            assert count == 2


class TestEncryptionParity:
    def test_encrypt_then_decrypt_roundtrip(self):
        """encrypt → decrypt returns original plaintext."""
        plaintext = "sk-roundtrip-abcdef1234567890"
        ciphertext = encrypt_api_key(plaintext)
        assert ciphertext != plaintext
        assert decrypt_api_key(ciphertext) == plaintext

    def test_mask_api_key_format(self):
        """mask_api_key produces prefix***suffix form."""
        key = "sk-testkey1234abcd"
        masked = mask_api_key(key)
        assert masked.startswith("sk-")
        assert "..." in masked
        assert masked.endswith(key[-4:])

    def test_mask_short_key(self):
        """Keys with 8 or fewer chars are fully masked."""
        assert mask_api_key("short") == "***"
        assert mask_api_key("12345678") == "***"

    def test_to_dict_masked_key_matches_mask_function(self, app):
        """AIProviderKey.to_dict() masked_key equals mask_api_key(plaintext)."""
        plaintext = "sk-maskcheck-xyzzy9876"
        encrypted = encrypt_api_key(plaintext)
        with app.app_context():
            row = AIProviderKey(provider="openai", api_key_encrypted=encrypted)
            db.session.add(row)
            db.session.commit()
            result = db.session.get(AIProviderKey, row.id).to_dict()

        expected_mask = mask_api_key(plaintext)
        assert result["masked_key"] == expected_mask
